services:
  app:
    build: .
    container_name: commit-message-generator
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    ports:
      - "4040:4040"
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c"]
    command: |
      'if [ -n "$${NGROK_URL}" ]; then
        ngrok http --domain=$${NGROK_URL} app:8000;
      else
        ngrok http app:8000;
      fi'
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge